name: Test application

on:
  push:
  pull_request:
    types:
      - reopened

env:
  CLOUDAMQP_URL: "amqp://virtualjudge:virtualjudge@localhost:5672//"
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: virtualjudge
  POSTGRES_PASSWORD: virtualjudge
  POSTGRES_DB: virtualjudge

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.12.9-alpine
        env:
          RABBITMQ_DEFAULT_USER: virtualjudge
          RABBITMQ_DEFAULT_PASS: virtualjudge
        ports:
          - 5672:5672
      postgresql:
        image: postgres:16.0-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: virtualjudge
          POSTGRES_PASSWORD: virtualjudge
          POSTGRES_DB: virtualjudge
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.6.1"]
    env:
      DATABASE_URL: "postgres://virtualjudge:virtualjudge@localhost:5432/virtualjudge"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: false
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry run pip install --no-deps --upgrade pip
          poetry install --with dev

      - name: Run hooks
        uses: pre-commit/action@v3.0.0

      - name: Run tests
        run: |
          poetry run python manage.py test \
            --settings=server.settings.development
